### PR TITLE
Rename Atom Shell to Electron

### PR DESCRIPTION
**Pull request by mnquintana**
[Atom Shell is now Electron](http://blog.atom.io/2015/04/23/electron.html) - this PR renames stuff.

/cc @tbranyen

### CODE REVIEW

**Comment by tbranyen** [comment]
Awesome, thank you very much for this update!

**Comment by tbranyen** [comment]
Urgh, I should have done a better job reviewing this change.  You updated dynamically generated files, so I'll backport the changes into NodeGit

**Comment by mnquintana** [comment]
Whoops, sorry! I didn't realize these files were generated from the main NodeGit repo.

**Comment by tbranyen** [comment]
No worries, that was our fault for not making it clearer.  I applied your patch to the main NodeGit repository, you can see it here: https://github.com/nodegit/nodegit/commit/79e9022e0a05c2aef71ba5d23ffd5e7b9dd053a4

**Pull request merged**
