### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ghedamat**

### CODE REVIEW

**Comment by johnhaley81** [comment]
Thanks!

**Comment by johnhaley81** [comment]
Whoops, I just noticed this is into nodegit.github.com which is auto-generated from nodegit. You can fix this by modifying https://github.com/nodegit/nodegit/blob/master/guides/repositories/README.md

**Comment by ghedamat** [comment]
done! https://github.com/nodegit/nodegit/pull/888

sorry I missed that it was in the other repo :)

**Comment by johnhaley81** [comment]
No worries!

**Pull request closed without merging**
